services:
  development:
    image: bxt_development:latest
    build:
      context: .
      target: development
    ports:
      - "8080:8080"

  production:
    image: bxt_production:latest
    build:
      context: .
      target: production
    ports:
      - "80:8080"
    volumes:
      - persistence_volume:/app/persistence/
volumes:
  persistence_volume:
