services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  production:
    ports: !reset []
    networks:
      - caddy
    labels:
      caddy: "${CADDY_HOST}"
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
