branches: [unstable, testing, stable]
(alpm.sync):
  sync-branches: [unstable]
repositories:
  [core]:
    architecture: x86_64
    (alpm.sync):
      repo-url: "cloudflaremirrors.com"
      repo-structure-template: "/archlinux/{repository}/os/{architecture}"
    (box.pool):
      template: "/{location}/"

  [core]:
    architecture: aarch64
    (alpm.sync):
      repo-url: "de3.mirror.archlinuxarm.org"
      repo-structure-template: "/{architecture}/{repository}"
    (box.pool):
      template: "/{location}-arm/"
