branches: [unstable, testing, stable]
(alpm.sync):
  sync-branches: [unstable]
repositories:
  [core, extra, multilib]:
    architecture: x86_64
    (alpm.sync):
      repo-url: "repo.manjaro.org"
      repo-structure-template: "/repo/{branch}/{repository}/{architecture}"
    (box.pool):
      template: "/{location}/"

  [core, extra]:
    architecture: aarch64
    (alpm.sync):
      repo-url: "repo.manjaro.org"
      repo-structure-template: "/repo/arm-{branch}/{repository}/{architecture}"
    (box.pool):
      template: "/{location}-arm/"
