name: Build with docker
on: [push, pull_request]

jobs:
  build-docker:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Build production environment using docker-compose
        run: |
          docker-compose -f docker-compose.yml build production
