name: Build Docker Image
on:
  workflow_call:
    inputs:
      tags:
        description: List of tags of the resulting Docker image
        required: true
        type: string
      target:
        description: Sets the target stage to build
        required: true
        type: string

jobs:
  build-docker:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          target: ${{ inputs.target }}
          tags: ${{ inputs.tags }}
          cache-from: type=gha,scope=${{ inputs.target }}
          cache-to: type=gha,mode=max,scope=${{ inputs.target }}
          outputs: type=docker,dest=./bxt-${{ inputs.target }}.tar

      - name: Upload Docker image to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bxt-${{ inputs.target }}-image
          path: |
            bxt-${{ inputs.target }}.tar
            docker-compose.yml
            docker-compose.caddy.yml
