# SPDX-FileCopyrightText: 2024 Roman Gilg <romangg@manjaro.org>
# SPDX-License-Identifier: MIT
name: CI
on:
  - push
  - pull_request

jobs:
  message-lint:
    uses: ./.github/workflows/commit-lint.yml
    with:
      upstream-repo: https://github.com/anydistro/bxt.git
  check-format:
    uses: ./.github/workflows/check-format.yml

  prod-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      tags: anydistro/bxt:latest
      target: production
  dev-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      tags: anydistro/bxt-development:latest
      target: development

  analysis:
    uses: ./.github/workflows/analysis.yml
    needs: dev-build
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: prod-build
    secrets: inherit
